version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=your_password
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    shm_size: '2gb'

volumes:
  oracle_data: 
