name: Deploy .NET to Heroku (source)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unshallow repository
        run: git fetch --prune --unshallow

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/practical-test-api.git || true
          git push --force heroku main:main 
